# Generated by Django 4.2.7 on 2025-03-20 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworksubmission',
            name='completion_status',
            field=models.CharField(blank=True, choices=[('completed', 'Выполнено'), ('partially_completed', 'Частично выполнено'), ('not_completed', 'Не выполнено')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='homeworksubmission',
            name='teacher_comment',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
