# Generated by Django 4.2.7 on 2025-03-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_homeworksubmission_completion_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='teacher_percentage',
            field=models.IntegerField(default=0, help_text='Процент от стоимости занятия, который получает преподаватель'),
        ),
    ]
