# Generated by Django 4.2.7 on 2025-03-24 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_class_teacher_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='teacher_fixed_payment',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Фиксированная оплата преподавателя за занятие', max_digits=10),
        ),
        migrations.AddField(
            model_name='class',
            name='teacher_payment_type',
            field=models.CharField(choices=[('percentage', 'Процент от стоимости урока'), ('fixed', 'Фиксированная оплата')], default='percentage', help_text='Тип оплаты преподавателя', max_length=10),
        ),
    ]
