# Generated by Django 4.2.7 on 2025-04-20 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_class_teacher_fixed_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='due_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Срок сдачи'),
        ),
        migrations.AddField(
            model_name='homework',
            name='title',
            field=models.CharField(default='Домашнее задание', max_length=255, verbose_name='Название'),
        ),
    ]
