# Generated by Django 4.2.7 on 2025-04-20 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0006_add_missing_fields_to_homework'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Активен ли ученик в данном классе', verbose_name='Активен'),
        ),
    ]
