# Generated by Django 4.2.7 on 2025-04-20 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0007_add_is_active_to_enrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='date',
            field=models.DateField(null=True, blank=True, verbose_name="Дата", db_index=True),
        ),
    ]
