# Generated by Django 4.2.7 on 2025-04-20 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0008_make_date_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworksubmission',
            name='grade',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Оценка за выполненное домашнее задание', null=True, verbose_name='Оценка'),
        ),
    ]
