# Generated by Django 4.2.7 on 2025-05-13 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0012_class_updated_at_alter_class_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='classworkfile',
            name='material_type',
            field=models.CharField(choices=[('general', 'Общий материал'), ('lesson_specific', 'Материал к конкретному уроку')], db_index=True, default='general', max_length=20, verbose_name='Тип материала'),
        ),
        migrations.AddField(
            model_name='classworkfile',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='classes.classschedule', verbose_name='Занятие по расписанию'),
        ),
        migrations.AddIndex(
            model_name='classworkfile',
            index=models.Index(fields=['material_type'], name='classes_cla_materia_470c55_idx'),
        ),
        migrations.AddIndex(
            model_name='classworkfile',
            index=models.Index(fields=['schedule'], name='classes_cla_schedul_44a1b3_idx'),
        ),
    ]
