# Generated by Django 4.2.7 on 2025-05-26 11:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_user_user_type_marketer'),
        ('classes', '0013_classworkfile_material_type_classworkfile_schedule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentLessonGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.PositiveSmallIntegerField(help_text='Оценка за урок (от 0 до 100)', verbose_name='Оценка')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий преподавателя')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата урока')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_grades', to='classes.classschedule', verbose_name='Расписание')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_grades', to='accounts.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Оценка за урок',
                'verbose_name_plural': 'Оценки за уроки',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['student', 'schedule'], name='classes_stu_student_be92e0_idx'), models.Index(fields=['student', '-date'], name='classes_stu_student_e0e168_idx')],
                'unique_together': {('student', 'schedule', 'date')},
            },
        ),
        migrations.CreateModel(
            name='LessonMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('file', models.FileField(blank=True, null=True, upload_to='lesson_materials/', verbose_name='Файл')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_materials', to='classes.class', verbose_name='Класс')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_materials', to='classes.classschedule', verbose_name='Расписание')),
            ],
            options={
                'verbose_name': 'Материал урока',
                'verbose_name_plural': 'Материалы уроков',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['class_obj', 'schedule'], name='classes_les_class_o_ec1073_idx'), models.Index(fields=['-created_at'], name='classes_les_created_68c530_idx')],
            },
        ),
    ]
