# Generated by Django 4.2.7 on 2025-05-29 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_user_user_type_marketer'),
        ('classes', '0014_studentlessongrade_lessonmaterial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonScheduledLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Название урока')),
                ('date', models.DateField(db_index=True, verbose_name='Дата урока')),
                ('time', models.TimeField(verbose_name='Время урока')),
                ('duration', models.IntegerField(default=60, verbose_name='Продолжительность (минуты)')),
                ('lesson_type', models.CharField(choices=[('trial', 'Пробный'), ('regular', 'Обычный')], db_index=True, default='regular', max_length=10, verbose_name='Тип урока')),
                ('trial_status', models.CharField(blank=True, choices=[('pending', 'Ожидает решения'), ('continued', 'Продолжил обучение'), ('discontinued', 'Не продолжил обучение')], db_index=True, default='pending', max_length=15, null=True, verbose_name='Статус пробного урока')),
                ('price_per_student', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость для ученика')),
                ('teacher_payment', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Оплата преподавателю')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Урок проведен')),
                ('is_paid_to_teacher', models.BooleanField(default=False, verbose_name='Оплачено преподавателю')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('students', models.ManyToManyField(related_name='non_scheduled_lessons', to='accounts.student', verbose_name='Ученики')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='non_scheduled_lessons', to='accounts.teacher', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Урок не по расписанию',
                'verbose_name_plural': 'Уроки не по расписанию',
                'ordering': ['-date', '-time'],
            },
        ),
        migrations.CreateModel(
            name='NonScheduledLessonAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_present', models.BooleanField(default=False, verbose_name='Присутствовал')),
                ('marked_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Кто отметил')),
                ('marked_at', models.DateTimeField(auto_now_add=True, verbose_name='Когда отмечено')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='classes.nonscheduledlesson', verbose_name='Урок')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='non_scheduled_attendances', to='accounts.student', verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Посещаемость внепланового урока',
                'verbose_name_plural': 'Посещаемость внеплановых уроков',
                'unique_together': {('lesson', 'student')},
            },
        ),
        migrations.AddIndex(
            model_name='nonscheduledlesson',
            index=models.Index(fields=['name'], name='classes_non_name_154637_idx'),
        ),
        migrations.AddIndex(
            model_name='nonscheduledlesson',
            index=models.Index(fields=['teacher'], name='classes_non_teacher_6fef98_idx'),
        ),
        migrations.AddIndex(
            model_name='nonscheduledlesson',
            index=models.Index(fields=['date'], name='classes_non_date_36d1f8_idx'),
        ),
        migrations.AddIndex(
            model_name='nonscheduledlesson',
            index=models.Index(fields=['lesson_type'], name='classes_non_lesson__035336_idx'),
        ),
        migrations.AddIndex(
            model_name='nonscheduledlesson',
            index=models.Index(fields=['trial_status'], name='classes_non_trial_s_c4ac6b_idx'),
        ),
    ]
