# Generated by Django 4.2.7 on 2025-03-20 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_reception'),
        ('finance', '0003_alter_transaction_options_transaction_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='Первый день месяца')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to='accounts.teacher')),
            ],
            options={
                'verbose_name': 'Зарплата учителя',
                'verbose_name_plural': 'Зарплаты учителей',
                'ordering': ['-month'],
                'unique_together': {('teacher', 'month')},
            },
        ),
    ]
