# Generated by Django 4.2.7 on 2025-03-24 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_teachersalary'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachersalary',
            name='lessons_count',
            field=models.PositiveIntegerField(default=0, help_text='Количество проведенных занятий'),
        ),
    ]
