# Generated by Django 4.2.7 on 2025-04-22 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0010_alter_class_options_alter_classschedule_options_and_more'),
        ('accounts', '0011_alter_parent_options_alter_reception_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0005_teachersalary_lessons_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='BenchmarkSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(db_index=True, max_length=100, verbose_name='Должность')),
                ('min_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Минимальная зарплата')),
                ('max_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Максимальная зарплата')),
                ('average_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Средняя зарплата')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Эталонная зарплата',
                'verbose_name_plural': 'Эталонные зарплаты',
                'ordering': ['position'],
            },
        ),
        migrations.AlterModelOptions(
            name='teachersalary',
            options={'ordering': ['-month'], 'verbose_name': 'Зарплата преподавателя', 'verbose_name_plural': 'Зарплаты преподавателей'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date'], 'verbose_name': 'Транзакция', 'verbose_name_plural': 'Транзакции'},
        ),
        migrations.AlterField(
            model_name='teachersalary',
            name='amount',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=10, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='teachersalary',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='teachersalary',
            name='is_paid',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Оплачено'),
        ),
        migrations.AlterField(
            model_name='teachersalary',
            name='lessons_count',
            field=models.IntegerField(default=0, verbose_name='Количество занятий'),
        ),
        migrations.AlterField(
            model_name='teachersalary',
            name='month',
            field=models.DateField(db_index=True, help_text='Первый день месяца', verbose_name='Месяц'),
        ),
        migrations.AlterField(
            model_name='teachersalary',
            name='paid_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выплаты'),
        ),
        migrations.AlterField(
            model_name='teachersalary',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to='accounts.teacher', verbose_name='Преподаватель'),
        ),
        migrations.AlterField(
            model_name='teachersalary',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=10, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='class_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='classes.class', verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Создано пользователем'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(db_index=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.student', verbose_name='Ученик'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('payment', 'Оплата'), ('deposit', 'Депозит'), ('refund', 'Возврат')], db_index=True, max_length=10, verbose_name='Тип транзакции'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата обновления'),
        ),
        migrations.AddIndex(
            model_name='teachersalary',
            index=models.Index(fields=['teacher'], name='finance_tea_teacher_b07b90_idx'),
        ),
        migrations.AddIndex(
            model_name='teachersalary',
            index=models.Index(fields=['-month'], name='finance_tea_month_8bf514_idx'),
        ),
        migrations.AddIndex(
            model_name='teachersalary',
            index=models.Index(fields=['is_paid'], name='finance_tea_is_paid_1aab24_idx'),
        ),
        migrations.AddIndex(
            model_name='teachersalary',
            index=models.Index(fields=['amount'], name='finance_tea_amount_5bf9f5_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['student'], name='finance_tra_student_38322f_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_type'], name='finance_tra_transac_2a23c2_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['-date'], name='finance_tra_date_7b7e25_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['amount'], name='finance_tra_amount_84277c_idx'),
        ),
    ]
