# Generated by Django 4.2.7 on 2025-05-02 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0006_benchmarksalary_alter_teachersalary_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachersalary',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_salaries', to=settings.AUTH_USER_MODEL, verbose_name='Кто подтвердил выплату'),
        ),
    ]
