# Generated by Django 4.2.7 on 2025-05-21 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0007_teachersalary_confirmed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachersalary',
            name='advance_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма аванса'),
        ),
        migrations.AddField(
            model_name='teachersalary',
            name='advance_confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_advances', to=settings.AUTH_USER_MODEL, verbose_name='Аванс подтвержден пользователем'),
        ),
        migrations.AddField(
            model_name='teachersalary',
            name='advance_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выплаты аванса'),
        ),
        migrations.AddField(
            model_name='teachersalary',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Положительное значение - долг учителю, отрицательное - долг учителя', max_digits=10, verbose_name='Баланс после выплат'),
        ),
    ]
