# Generated by Django 4.2.7 on 2025-05-21 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_teachersalary_advance_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachersalary',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Не оплачено'), ('partially_paid', 'Частично оплачено'), ('paid', 'Оплачено полностью')], db_index=True, default='unpaid', max_length=20, verbose_name='Статус оплаты'),
        ),
    ]
