# Generated by Django 4.2.7 on 2025-05-24 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0009_teachersalary_payment_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teachersalary',
            options={'ordering': ['-month', 'teacher'], 'verbose_name': 'Зарплата преподавателя', 'verbose_name_plural': 'Зарплаты преподавателей'},
        ),
        migrations.RemoveIndex(
            model_name='teachersalary',
            name='finance_tea_is_paid_1aab24_idx',
        ),
        migrations.RemoveField(
            model_name='teachersalary',
            name='advance_date',
        ),
        migrations.RemoveField(
            model_name='teachersalary',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='teachersalary',
            name='confirmed_by',
        ),
        migrations.RemoveField(
            model_name='teachersalary',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='teachersalary',
            name='paid_date',
        ),
        migrations.AddField(
            model_name='teachersalary',
            name='advance_paid_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выплаты аванса'),
        ),
        migrations.AddField(
            model_name='teachersalary',
            name='final_payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончательной выплаты'),
        ),
        migrations.AddField(
            model_name='teachersalary',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Выплачено за месяц'),
        ),
        migrations.AddField(
            model_name='teachersalary',
            name='payment_confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_final_payments', to=settings.AUTH_USER_MODEL, verbose_name='Выплата подтверждена'),
        ),
        migrations.AlterField(
            model_name='teachersalary',
            name='advance_confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_advances', to=settings.AUTH_USER_MODEL, verbose_name='Аванс подтвержден'),
        ),
        migrations.AlterField(
            model_name='teachersalary',
            name='amount',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=10, verbose_name='Начислено (общая сумма за месяц)'),
        ),
        migrations.AlterField(
            model_name='teachersalary',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Не выплачено'), ('partially_paid', 'Частично выплачено'), ('paid', 'Выплачено полностью')], db_index=True, default='unpaid', max_length=20, verbose_name='Статус выплаты'),
        ),
        migrations.AddIndex(
            model_name='teachersalary',
            index=models.Index(fields=['payment_status'], name='finance_tea_payment_334b39_idx'),
        ),
        migrations.AddIndex(
            model_name='teachersalary',
            index=models.Index(fields=['paid_amount'], name='finance_tea_paid_am_b59412_idx'),
        ),
    ]
