# Generated by Django 4.2.7 on 2025-03-20 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_parent_students_parent_full_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='google_docs_link',
        ),
        migrations.AddField(
            model_name='teacher',
            name='docs_link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на документы'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
