# Generated by Django 4.2.7 on 2025-03-20 05:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_teacher_google_docs_link_teacher_docs_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('docs_link', models.URLField(blank=True, null=True, verbose_name='Ссылка на документы')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reception_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
