# Generated by Django 4.2.7 on 2025-04-03 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_reception'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='face_id_data',
            field=models.TextField(blank=True, help_text='Данные для распознавания лица', null=True),
        ),
    ]
