# Generated by Django 4.2.7 on 2025-04-17 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_face_id_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='reception',
            name='face_image',
            field=models.ImageField(blank=True, null=True, upload_to='face_images/receptions/', verbose_name='Фото лица для FaceID'),
        ),
        migrations.AddField(
            model_name='student',
            name='face_image',
            field=models.ImageField(blank=True, null=True, upload_to='face_images/students/', verbose_name='Фото лица для FaceID'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='face_image',
            field=models.ImageField(blank=True, null=True, upload_to='face_images/teachers/', verbose_name='Фото лица для FaceID'),
        ),
    ]
