# Generated by Django 4.2.7 on 2025-04-20 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_student_is_self_managed'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='current_grade',
            field=models.IntegerField(db_index=True, default=1, help_text='В каком классе сейчас учится ученик (1-11)', verbose_name='Текущий класс'),
        ),
        migrations.AlterField(
            model_name='student',
            name='school_start_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Год начала обучения'),
        ),
    ]
