# Generated by Django 4.2.7 on 2025-04-22 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_add_current_grade_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parent',
            options={'verbose_name': 'Родитель', 'verbose_name_plural': 'Родители'},
        ),
        migrations.AlterModelOptions(
            name='reception',
            options={'verbose_name': 'Администратор рецепции', 'verbose_name_plural': 'Администраторы рецепции'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Ученик', 'verbose_name_plural': 'Ученики'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Преподаватель', 'verbose_name_plural': 'Преподаватели'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='parent',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='parent_type',
            field=models.CharField(choices=[('parent', 'Родитель'), ('student', 'Ученик')], db_index=True, default='parent', help_text='Тип родителя: настоящий родитель или ученик в роли родителя', max_length=10, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='reception',
            name='birth_date',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='reception',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='reception',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='student',
            name='balance',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=10, verbose_name='Баланс'),
        ),
        migrations.AlterField(
            model_name='student',
            name='birth_date',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='student',
            name='full_name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='student',
            name='graduation_year',
            field=models.IntegerField(db_index=True, verbose_name='Год выпуска'),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='accounts.parent', verbose_name='Родитель'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.CharField(max_length=100, verbose_name='Школа'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='birth_date',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('reception', 'Reception'), ('teacher', 'Teacher'), ('student', 'Student'), ('parent', 'Parent')], db_index=True, max_length=10, verbose_name='Тип пользователя'),
        ),
        migrations.AddIndex(
            model_name='parent',
            index=models.Index(fields=['full_name'], name='accounts_pa_full_na_34cab9_idx'),
        ),
        migrations.AddIndex(
            model_name='parent',
            index=models.Index(fields=['phone_number'], name='accounts_pa_phone_n_1b5dba_idx'),
        ),
        migrations.AddIndex(
            model_name='parent',
            index=models.Index(fields=['parent_type'], name='accounts_pa_parent__e93a18_idx'),
        ),
        migrations.AddIndex(
            model_name='reception',
            index=models.Index(fields=['full_name'], name='accounts_re_full_na_62dc57_idx'),
        ),
        migrations.AddIndex(
            model_name='reception',
            index=models.Index(fields=['phone_number'], name='accounts_re_phone_n_03ab40_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['full_name'], name='accounts_st_full_na_157e91_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['current_grade'], name='accounts_st_current_ea130c_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['graduation_year'], name='accounts_st_graduat_7043ef_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['balance'], name='accounts_st_balance_0a1234_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['full_name'], name='accounts_te_full_na_631c53_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['phone_number'], name='accounts_te_phone_n_524eb0_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['user_type'], name='accounts_us_user_ty_b6cfc8_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='accounts_us_usernam_c0ea66_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='accounts_us_email_74c8d6_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active'], name='accounts_us_is_acti_a5841d_idx'),
        ),
    ]
