# Generated by Django 4.2.7 on 2025-04-30 13:14

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_parent_options_alter_reception_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='face_image',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.student_face_image_path, verbose_name='Фото лица для FaceID'),
        ),
    ]
