# Generated by Django 4.2.7 on 2025-05-19 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_student_face_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('reception', 'Reception'), ('teacher', 'Teacher'), ('student', 'Student'), ('parent', 'Parent'), ('marketer', 'Marketer')], db_index=True, max_length=10, verbose_name='Тип пользователя'),
        ),
        migrations.CreateModel(
            name='Marketer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('docs_link', models.URLField(blank=True, null=True, verbose_name='Ссылка на документы')),
                ('face_image', models.ImageField(blank=True, null=True, upload_to='face_images/marketers/', verbose_name='Фото лица для FaceID')),
                ('specialization', models.CharField(blank=True, max_length=100, null=True, verbose_name='Специализация')),
                ('skills', models.TextField(blank=True, null=True, verbose_name='Навыки')),
                ('experience_years', models.PositiveSmallIntegerField(default=0, verbose_name='Опыт работы (в годах)')),
                ('leads_target', models.PositiveIntegerField(default=0, verbose_name='Цель по лидам (в месяц)')),
                ('conversion_target', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Цель по конверсии (%)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='marketer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Маркетолог',
                'verbose_name_plural': 'Маркетологи',
                'indexes': [models.Index(fields=['full_name'], name='accounts_ma_full_na_726de8_idx'), models.Index(fields=['phone_number'], name='accounts_ma_phone_n_f0b7d0_idx'), models.Index(fields=['specialization'], name='accounts_ma_special_1c1a2e_idx')],
            },
        ),
    ]
