# Generated by Django 4.2.7 on 2025-06-21 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_telegrambroadcast_telegramuser_telegrammessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappbroadcast',
            name='target_grade',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11')], help_text='Выберите класс обучения (1-11) для фильтрации получателей', null=True, verbose_name='Класс обучения'),
        ),
    ]
