# Generated by Django 4.2.7 on 2025-05-19 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0013_alter_user_user_type_marketer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название кампании')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('scheduled', 'Запланирована'), ('active', 'Активна'), ('paused', 'Приостановлена'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], default='draft', max_length=20, verbose_name='Статус')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Бюджет')),
                ('spent', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Потрачено')),
                ('leads_goal', models.PositiveIntegerField(verbose_name='Цель по лидам')),
                ('conversion_goal', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Цель по конверсии (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('manager', models.ForeignKey(limit_choices_to={'user_type': 'marketer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_campaigns', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер кампании')),
            ],
            options={
                'verbose_name': 'Кампания',
                'verbose_name_plural': 'Кампании',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('in_progress', 'В работе'), ('qualified', 'Квалифицирован'), ('converted', 'Конвертирован в студента'), ('closed', 'Закрыт (отказ)')], default='new', max_length=20, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примечания')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('school', models.CharField(blank=True, max_length=100, null=True, verbose_name='Школа')),
                ('current_grade', models.IntegerField(blank=True, null=True, verbose_name='Текущий класс')),
                ('parent_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='ФИО родителя')),
                ('parent_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон родителя')),
                ('interested_subjects', models.TextField(blank=True, null=True, verbose_name='Интересующие предметы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('meta_data', models.JSONField(blank=True, null=True, verbose_name='Метаданные')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный маркетолог')),
                ('converted_to_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_from_lead', to='accounts.student', verbose_name='Конвертирован в студента')),
            ],
            options={
                'verbose_name': 'Лид',
                'verbose_name_plural': 'Лиды',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название источника')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Источник лида',
                'verbose_name_plural': 'Источники лидов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SaleStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название этапа')),
                ('order', models.PositiveSmallIntegerField(verbose_name='Порядок отображения')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание этапа')),
                ('conversion_goal', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Целевая конверсия (%)')),
                ('color', models.CharField(default='#3498db', max_length=20, verbose_name='Цвет этапа')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Этап воронки продаж',
                'verbose_name_plural': 'Этапы воронки продаж',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SocialMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('instagram', 'Instagram DM'), ('facebook', 'Facebook Messenger')], max_length=20, verbose_name='Платформа')),
                ('direction', models.CharField(choices=[('incoming', 'Входящее'), ('outgoing', 'Исходящее')], max_length=10, verbose_name='Направление')),
                ('sender_id', models.CharField(max_length=100, verbose_name='ID отправителя')),
                ('sender_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя отправителя')),
                ('message_text', models.TextField(verbose_name='Текст сообщения')),
                ('timestamp', models.DateTimeField(verbose_name='Время сообщения')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('meta_data', models.JSONField(blank=True, null=True, verbose_name='Метаданные')),
                ('assigned_to', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'marketer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_messages', to=settings.AUTH_USER_MODEL, verbose_name='Назначено')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_messages', to='crm.lead', verbose_name='Лид')),
            ],
            options={
                'verbose_name': 'Сообщение из соцсети',
                'verbose_name_plural': 'Сообщения из соцсетей',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MetaBusinessAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название аккаунта')),
                ('page_id', models.CharField(max_length=100, verbose_name='ID страницы')),
                ('access_token', models.TextField(verbose_name='Токен доступа')),
                ('token_expires_at', models.DateTimeField(verbose_name='Срок действия токена')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('marketers', models.ManyToManyField(limit_choices_to={'user_type': 'marketer'}, related_name='meta_accounts', to=settings.AUTH_USER_MODEL, verbose_name='Маркетологи')),
            ],
            options={
                'verbose_name': 'Аккаунт Meta Business',
                'verbose_name_plural': 'Аккаунты Meta Business',
            },
        ),
        migrations.CreateModel(
            name='LeadStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entered_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата перехода на этап')),
                ('exited_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата выхода из этапа')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примечания')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_status_changes', to=settings.AUTH_USER_MODEL, verbose_name='Кем изменен')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='crm.lead', verbose_name='Лид')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_history', to='crm.salestage', verbose_name='Этап')),
            ],
            options={
                'verbose_name': 'История статуса лида',
                'verbose_name_plural': 'История статусов лидов',
                'ordering': ['-entered_at'],
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='current_stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_leads', to='crm.salestage', verbose_name='Текущий этап'),
        ),
        migrations.AddField(
            model_name='lead',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='crm.leadsource', verbose_name='Источник'),
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('call', 'Звонок'), ('email', 'Email'), ('meeting', 'Встреча'), ('whatsapp', 'WhatsApp'), ('instagram', 'Instagram'), ('other', 'Другое')], max_length=20, verbose_name='Тип взаимодействия')),
                ('date_time', models.DateTimeField(verbose_name='Дата и время')),
                ('duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='Длительность (в минутах)')),
                ('result', models.CharField(choices=[('positive', 'Положительный'), ('neutral', 'Нейтральный'), ('negative', 'Отрицательный'), ('no_answer', 'Нет ответа')], max_length=20, verbose_name='Результат')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примечания')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='crm/interactions/', verbose_name='Вложение')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='crm.lead', verbose_name='Лид')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_interactions', to=settings.AUTH_USER_MODEL, verbose_name='Кем выполнено')),
            ],
            options={
                'verbose_name': 'Взаимодействие',
                'verbose_name_plural': 'Взаимодействия',
                'ordering': ['-date_time'],
            },
        ),
        migrations.CreateModel(
            name='CampaignChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_type', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('google', 'Google Ads'), ('email', 'Email рассылка'), ('sms', 'SMS рассылка'), ('offline', 'Офлайн реклама'), ('other', 'Другое')], max_length=20, verbose_name='Тип канала')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Бюджет канала')),
                ('spent', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Потрачено')),
                ('impressions', models.PositiveIntegerField(default=0, verbose_name='Показы')),
                ('clicks', models.PositiveIntegerField(default=0, verbose_name='Клики')),
                ('leads_generated', models.PositiveIntegerField(default=0, verbose_name='Сгенерировано лидов')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='crm.campaign', verbose_name='Кампания')),
            ],
            options={
                'verbose_name': 'Канал кампании',
                'verbose_name_plural': 'Каналы кампаний',
            },
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['full_name'], name='crm_lead_full_na_656b51_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['phone_number'], name='crm_lead_phone_n_d5ebab_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status'], name='crm_lead_status_2c1bc7_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['created_at'], name='crm_lead_created_d9bbc3_idx'),
        ),
    ]
