# Generated by Django 4.2.7 on 2025-04-03 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_user_face_id_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0003_attendance_is_canceled_attendance_substitute_teacher_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceRecognitionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=False)),
                ('confidence', models.FloatField(default=0.0, help_text='Уровень уверенности распознавания (0-1)')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_info', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_recognition_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Лог распознавания лица',
                'verbose_name_plural': 'Логи распознавания лиц',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='FaceAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('confidence', models.FloatField(default=0.0, help_text='Уровень уверенности распознавания (0-1)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='face_attendance/')),
                ('attendance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='face_attendance', to='attendance.attendance')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_attendances', to='accounts.student')),
            ],
            options={
                'verbose_name': 'Отметка посещаемости по лицу',
                'verbose_name_plural': 'Отметки посещаемости по лицу',
                'ordering': ['-timestamp'],
            },
        ),
    ]
