# Generated by Django 4.2.7 on 2025-04-03 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('face_recognition_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faceattendance',
            name='student',
        ),
    ]
