# Generated by Django 4.2.7 on 2025-03-15 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('homework_mark', models.CharField(blank=True, choices=[('completed', 'Completed'), ('partial', 'Partially Completed'), ('not_completed', 'Not Completed')], max_length=15, null=True)),
                ('activity_mark', models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('normal', 'Normal'), ('poor', 'Poor')], max_length=10, null=True)),
                ('teacher_comment', models.CharField(blank=True, max_length=150, null=True)),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='classes.class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='accounts.student')),
            ],
            options={
                'unique_together': {('student', 'class_obj', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('excused', 'Excused')], default='absent', max_length=10)),
                ('teacher_confirmed', models.BooleanField(default=False)),
                ('reception_confirmed', models.BooleanField(default=False)),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='classes.class')),
                ('class_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='classes.classschedule')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='accounts.student')),
            ],
            options={
                'unique_together': {('student', 'class_obj', 'date')},
            },
        ),
    ]
