# Generated by Django 4.2.7 on 2025-03-22 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanceledAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canceled_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(help_text='Причина отмены посещения (макс. 50 слов)', max_length=500)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancellations', to='attendance.attendance')),
                ('canceled_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canceled_attendances', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
