# Generated by Django 4.2.7 on 2025-03-24 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classes', '0004_class_teacher_fixed_payment_and_more'),
        ('accounts', '0004_reception'),
        ('attendance', '0002_canceledattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='is_canceled',
            field=models.BooleanField(default=False, help_text='Флаг, указывающий, что урок отменен'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='substitute_teacher',
            field=models.ForeignKey(blank=True, help_text='Заменяющий учитель', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substituted_attendances', to='accounts.teacher'),
        ),
        migrations.AddField(
            model_name='mark',
            name='substitute_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substitute_marks', to='accounts.teacher'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('excused', 'Excused'), ('canceled', 'Canceled')], default='absent', max_length=10),
        ),
        migrations.CreateModel(
            name='CancellationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Дата урока, который нужно отменить')),
                ('reason', models.TextField(help_text='Причина отмены урока', max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('approved', 'Подтверждено'), ('rejected', 'Отклонено')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('needs_substitute', models.BooleanField(default=False, help_text='Требуется ли заменяющий учитель')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_cancellations', to=settings.AUTH_USER_MODEL)),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancellation_requests', to='classes.class')),
                ('class_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancellation_requests', to='classes.classschedule')),
                ('substitute_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substitute_requests', to='accounts.teacher')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancellation_requests', to='accounts.teacher')),
            ],
            options={
                'verbose_name': 'Запрос на отмену урока',
                'verbose_name_plural': 'Запросы на отмену уроков',
                'ordering': ['-created_at'],
            },
        ),
    ]
