# Generated by Django 4.2.7 on 2025-04-21 15:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('attendance', '0003_attendance_is_canceled_attendance_substitute_teacher_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.FloatField(default=0.0, help_text='Уровень уверенности при распознавании лица')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('face_image', models.ImageField(blank=True, help_text='Изображение лица, использованное для распознавания', null=True, upload_to='face_attendance/')),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_attendances', to='attendance.attendance')),
                ('reception_confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_face_attendances', to='accounts.user')),
            ],
            options={
                'verbose_name': 'Посещаемость по лицу',
                'verbose_name_plural': 'Посещаемость по лицу',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='attendance',
            name='reception_confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_attendances', to='accounts.user'),
        ),
    ]
