# Generated by Django 4.2.7 on 2025-05-10 06:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_student_face_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classes', '0012_class_updated_at_alter_class_created_at'),
        ('attendance', '0004_auto_20250421_2027'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cancellationrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Запрос на отмену урока от учителя', 'verbose_name_plural': 'Запросы на отмену уроков от учителей'},
        ),
        migrations.CreateModel(
            name='StudentCancellationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Дата урока, который нужно отменить')),
                ('reason', models.TextField(help_text='Причина отмены урока', max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('approved', 'Подтверждено'), ('rejected', 'Отклонено')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendance', models.ForeignKey(blank=True, help_text='Связанная запись о посещаемости', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancellation_request', to='attendance.attendance')),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_cancellation_requests', to='classes.class')),
                ('class_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_cancellation_requests', to='classes.classschedule')),
                ('created_by', models.ForeignKey(help_text='Пользователь, создавший запрос (студент или родитель)', on_delete=django.db.models.deletion.CASCADE, related_name='created_student_cancellations', to=settings.AUTH_USER_MODEL)),
                ('processed_by', models.ForeignKey(blank=True, help_text='Пользователь, обработавший запрос (администратор или ресепшн)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_student_cancellations', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancellation_requests', to='accounts.student')),
            ],
            options={
                'verbose_name': 'Запрос на отмену урока от ученика',
                'verbose_name_plural': 'Запросы на отмену уроков от учеников',
                'ordering': ['-created_at'],
                'unique_together': {('student', 'class_obj', 'date')},
            },
        ),
    ]
