# Generated by Django 4.2.7 on 2025-05-13 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_alter_cancellationrequest_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Присутствует'), ('absent', 'Отсутствует'), ('excused', 'Уважительная причина'), ('canceled', 'Отменено')], default='absent', max_length=10),
        ),
    ]
