# Generated by Django 4.2.7 on 2025-05-13 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_alter_attendance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='face_id_confirmed',
            field=models.BooleanField(default=False, help_text='Флаг, указывающий, что посещаемость подтверждена через Face ID'),
        ),
    ]
